# © Muiris Woulfe
# Licensed under the MIT License

---

version: 2

updates:
  - directory: /
    package-ecosystem: nuget
    schedule:
      interval: daily
    labels:
      - dependencies
    assignees:
      - muiriswoulfe
    reviewers:
      - muiriswoulfe

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    assignees:
      - muiriswoulfe
    reviewers:
      - muiriswoulfe

...
