# © Muiris Woulfe
# Licensed under the MIT License

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/src/NuGet.TransitiveDependency.Finder.ConsoleApp/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/NuGet.TransitiveDependency.Finder/"
    schedule:
      interval: "daily"
