# © Muiris Woulfe
# Licensed under the MIT License

---

version: 2

updates:
  - directory: /src/NuGetTransitiveDependencyFinder.ConsoleApp/
    package-ecosystem: nuget
    schedule:
      interval: daily

  - directory: /src/NuGetTransitiveDependencyFinder/
    package-ecosystem: nuget
    schedule:
      interval: daily

...
