# © Muiris Woulfe
# Licensed under the MIT License

---

version: 2

updates:
  - directory: /src/Product/NuGetTransitiveDependencyFinder/
    package-ecosystem: nuget
    schedule:
      interval: daily

  - directory: /src/Product/NuGetTransitiveDependencyFinder.ConsoleApp/
    package-ecosystem: nuget
    schedule:
      interval: daily

  - directory: /src/Product/NuGetTransitiveDependencyFinder.UnitTests.ConsoleApp/
    package-ecosystem: nuget
    schedule:
      interval: daily

  - directory: /src/Product/NuGetTransitiveDependencyFinder.UnitTests/
    package-ecosystem: nuget
    schedule:
      interval: daily

...
