# © Muiris Woulfe
# Licensed under the MIT License

---

blank_issues_enabled: false

contact_links:
  - name: Support
    url: https://github.com/muiriswoulfe/NuGet-Transitive-Dependency-Finder/discussions
    about: Request support for the project

...
