# © Muiris Woulfe
# Licensed under the MIT License

---

extends: default

rules:
  comments-indentation: enable
  comments: enable
  document-end: enable
  document-start: enable
  empty-values: enable
  line-length:
    max: 120
  octal-values: enable
  quoted-strings:
    required: only-when-needed
  truthy:
    check-keys: false

...
